include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_empty_constructor_bodies: true
    avoid_unnecessary_containers: true
    unnecessary_this: true
    avoid_redundant_argument_values: true
    use_key_in_widget_constructors: true
    sort_constructors_first: true
    avoid_void_async: true
    prefer_final_locals: true
    prefer_final_fields: true
    constant_identifier_names: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/gen/**"

  errors:
    invalid_use_of_protected_member: warning
    invalid_annotation_target: ignore
